"""Realistic sample alerts for demos, testing and onboarding."""
from __future__ import annotations

SAMPLES: list[dict] = [
    {
        "id": "S-001",
        "name": "Encoded PowerShell from web service",
        "severity": "High",
        "tactic": "Execution",
        "alert": {
            "vendor": "Microsoft Defender",
            "title": "Suspicious PowerShell Encoded Command Detected",
            "description": "Defender telemetry: powershell.exe spawned by w3wp.exe with an encoded command argument and hidden window.",
            "severity": "High",
            "source_ip": "45.155.205.233",
            "endpoint_hostname": "FIN-WS-042",
            "user_account": "j.raman",
            "process_name": "powershell.exe",
            "command_line": "powershell.exe -w hidden -ep bypass -enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkA",
            "file_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "domain": "malicious-cdn.top",
            "url": "http://malicious-cdn.top/stage2.bin",
            "mitre_tactic": "Execution",
            "mitre_technique": "T1059.001",
            "timestamp": "2026-09-25T03:14:22Z",
        },
    },
    {
        "id": "S-002",
        "name": "Ransomware precursor: shadow copy deletion",
        "severity": "Critical",
        "tactic": "Impact",
        "alert": {
            "vendor": "CrowdStrike",
            "title": "Mass file modification + shadow copy deletion",
            "description": "Bulk rename operations across D:\\filevault followed by vssadmin shadow deletion and recovery disablement.",
            "severity": "Critical",
            "endpoint_hostname": "SRV-FILE-01",
            "user_account": "admin_svc",
            "process_name": "vssadmin.exe",
            "command_line": "vssadmin delete shadows /all /quiet && wbadmin delete catalog -quiet && bcdedit /set {default} recoveryenabled No",
            "file_path": "D:\\filevault\\finance\\q3_forecast.xlsx",
            "mitre_tactic": "Impact",
            "timestamp": "2026-09-25T04:02:11Z",
        },
    },
    {
        "id": "S-003",
        "name": "Password spray against domain accounts",
        "severity": "Medium",
        "tactic": "Credential Access",
        "alert": {
            "vendor": "Splunk",
            "title": "Anomalous authentication failure burst (Event ID 4625)",
            "description": "4625 failures from a single external source across 43 distinct domain accounts, max 4 attempts per account, then a single success.",
            "severity": "Medium",
            "source_ip": "185.220.101.7",
            "endpoint_hostname": "DC01",
            "user_account": "a.smith",
            "mitre_tactic": "Credential Access",
            "timestamp": "2026-09-25T02:47:03Z",
        },
    },
    {
        "id": "S-004",
        "name": "C2 beacon to suspicious domain",
        "severity": "High",
        "tactic": "Command and Control",
        "alert": {
            "vendor": "Zeek",
            "title": "Periodic outbound connection with low jitter",
            "description": "64 connections to the same host over 6 hours, inter-arrival mean 272s, standard deviation 9s.",
            "severity": "High",
            "source_ip": "10.20.44.117",
            "endpoint_hostname": "ENG-LT-207",
            "user_account": "j.raman",
            "domain": "cdn-sync-service.xyz",
            "url": "https://cdn-sync-service.xyz/api/v2/poll",
            "mitre_tactic": "Command and Control",
            "mitre_technique": "T1071",
            "timestamp": "2026-09-25T05:30:00Z",
        },
    },
    {
        "id": "S-005",
        "name": "Phishing attachment detonation",
        "severity": "Medium",
        "tactic": "Initial Access",
        "alert": {
            "vendor": "Proofpoint",
            "title": "Reported phishing message: invoice overdue",
            "description": "User reported a message impersonating the CFO. Sender domain registered 4 days ago with a free-mail reply-to.",
            "severity": "Medium",
            "endpoint_hostname": "HR-LT-114",
            "user_account": "m.kulkarni",
            "email_sender": "cfo.office@invoice-support-desk.ru",
            "file_hash": "5d41402abc4b2a76b9719d911017c592",
            "url": "http://invoice-support-desk.ru/portal/login",
            "mitre_tactic": "Initial Access",
            "mitre_technique": "T1566",
            "timestamp": "2026-09-25T06:11:45Z",
        },
    },
    {
        "id": "S-006",
        "name": "Log tampering: Windows event log cleared",
        "severity": "High",
        "tactic": "Defense Evasion",
        "alert": {
            "vendor": "Microsoft Sentinel",
            "title": "Security event log cleared (Event ID 1102)",
            "description": "wevtutil cl Security executed by a standard user account on a finance workstation.",
            "severity": "High",
            "endpoint_hostname": "FIN-WS-118",
            "user_account": "p.nair",
            "process_name": "wevtutil.exe",
            "command_line": "wevtutil cl Security",
            "mitre_tactic": "Defense Evasion",
            "mitre_technique": "T1070",
            "timestamp": "2026-09-25T04:58:09Z",
        },
    },
]


def by_id(sample_id: str) -> dict | None:
    for s in SAMPLES:
        if s["id"].lower() == str(sample_id).lower():
            return s
    return None
